name: Upload Website

on:
  workflow_call:
   inputs:
      username:
        required: false
        type: string
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git*/*'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACC_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SEC_KEY }}
        AWS_S3_BUCKET: ${{ inputs.username }}
        AWS_REGION: 'us-east-2'   # optional: defaults to us-east-1
      
