name: Upload Website

on:
  # schedule:
  #   - cron: "30 3 * * *"
  workflow_dispatch:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      AWS_ACC_KEY:
        required: true
      AWS_SEC_KEY:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git*/*'
      env:
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACC_KEY }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SEC_KEY }}
      # AWS_S3_BUCKET: ${{ secrets.username }}
       AWS_S3_BUCKET: ${{ inputs.foldername }}
       AWS_REGION: 'us-east-2'   # optional: defaults to us-east-1
      
