name: Upload Website

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      AWS_ACC_KEY:
        required: true
      AWS_SEC_KEY:
        required: true
        
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
         args: --acl public-read --follow-symlinks --delete --exclude '.git*/*'
         AWS_S3_BUCKET: ${{ inputs.username }}   
         aws-access-key-id: ${{ secrets.AWS_ACC_KEY }}
         aws-secret-access-key: ${{ secrets.AWS_SEC_KEY }}
         aws-region: 'us-east-2' 
         #aws-secret-access-key
#         with:
#           username: ${{ inputs.username }}   
#       - name: print the inputs
#         run: echo 
  
  
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@master
#     - uses: jakejarvis/s3-sync-action@master
#       with:
#         args: --acl public-read --follow-symlinks --delete --exclude '.git*/*'
#       env:
#         AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACC_KEY }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SEC_KEY }}
#         AWS_REGION: 'us-east-2'   # optional: defaults to us-east-1
